development:
  address: "smtp.mailgun.org"
  port: 587
  domain: "mailgun.org"
  authentication: "plain"
  user_name: <%= ENV["MAILGUN_DOMAIN"] %>
  password: <%= ENV["MAILGUN_PASSWORD"] %>
  enable_starttls_auto: true

production:
  address: "smtp.mailgun.org"
  port: 587
  domain: "mailgun.org"
  authentication: "plain"
  user_name: <%= ENV["MAILGUN_DOMAIN"] %>
  password: <%= ENV["MAILGUN_PASSWORD"] %>
  enable_starttls_auto: true
